require("dotenv").config();
const express=require("express"),crypto=require("crypto"),Database=require("better-sqlite3"),path=require("path");
const app=express(),PORT=process.env.PORT||3000,BOT_TOKEN=process.env.BOT_TOKEN||"";
const db=new Database("data.db"); db.pragma("journal_mode = WAL");
db.exec(`CREATE TABLE IF NOT EXISTS players(
telegram_id TEXT PRIMARY KEY,username TEXT,first_name TEXT,coins INTEGER DEFAULT 0,
best_score INTEGER DEFAULT 0,referrals INTEGER DEFAULT 0,skin TEXT DEFAULT 'classic',updated_at TEXT NOT NULL)`);
app.use(express.json({limit:"100kb"})); app.use(express.static(path.join(__dirname,"public")));
function user(req){try{let s=req.get("X-Telegram-Init-Data")||"",p=new URLSearchParams(s),h=p.get("hash");if(!BOT_TOKEN||!h)return null;p.delete("hash");let d=[...p].sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>`${k}=${v}`).join("\n"),key=crypto.createHmac("sha256","WebAppData").update(BOT_TOKEN).digest(),calc=crypto.createHmac("sha256",key).update(d).digest("hex");if(!crypto.timingSafeEqual(Buffer.from(calc),Buffer.from(h)))return null;return JSON.parse(p.get("user")||"{}")}catch{return null}}
function player(u){let id=String(u.id),p=db.prepare("SELECT * FROM players WHERE telegram_id=?").get(id);if(!p)db.prepare("INSERT INTO players(telegram_id,username,first_name,updated_at) VALUES(?,?,?,datetime('now'))").run(id,u.username||"",u.first_name||"");else db.prepare("UPDATE players SET username=?,first_name=?,updated_at=datetime('now') WHERE telegram_id=?").run(u.username||"",u.first_name||"",id);return db.prepare("SELECT * FROM players WHERE telegram_id=?").get(id)}
app.get("/api/me",(q,r)=>{let u=user(q);if(!u?.id)return r.status(401).json({error:"Telegram authorization required"});r.json({player:player(u)})});
app.get("/api/leaderboard",(q,r)=>r.json({leaderboard:db.prepare("SELECT username,first_name,best_score,coins FROM players ORDER BY best_score DESC,coins DESC LIMIT 20").all()}));
app.post("/api/score",(q,r)=>{let u=user(q);if(!u?.id)return r.status(401).json({error:"Telegram authorization required"});let p=player(u),score=Math.max(0,Math.min(100000,Number(q.body.score)||0)),coins=Math.max(0,Math.min(10000,Number(q.body.coins)||0));db.prepare("UPDATE players SET best_score=?,coins=coins+?,updated_at=datetime('now') WHERE telegram_id=?").run(Math.max(p.best_score,score),coins,String(u.id));r.json({player:player(u)})});
app.post("/api/profile",(q,r)=>{let u=user(q);if(!u?.id)return r.status(401).json({error:"Telegram authorization required"});let p=player(u),allowed={classic:0,fire:2000,ice:5000,gold:10000,cyber:20000},s=q.body.skin;if(!(s in allowed))return r.status(400).json({error:"Bad skin"});if(p.skin!==s){if(p.coins<allowed[s])return r.status(400).json({error:"Not enough coins"});db.prepare("UPDATE players SET coins=coins-?,skin=? WHERE telegram_id=?").run(allowed[s],s,String(u.id))}r.json({player:player(u)})});
app.listen(PORT,"0.0.0.0",()=>console.log("Snake Arena running on "+PORT));